import type { Metadata } from "next";
import "./globals.css";
import { VisualEditingProvider } from "../../direct-next/package/provider/visual-editing-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <VisualEditingProvider>
          {children}
        </VisualEditingProvider>
      </body>
    </html>
  );
}
