version: 1
directus: 11.10.2
vendor: postgres
collections:
  - collection: blocks
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: blocks
      color: null
      display_template: null
      group: null
      hidden: false
      icon: folder_code
      item_duplication_fields: null
      note: null
      preview_url: null
      singleton: false
      sort: 2
      sort_field: null
      translations: null
      unarchive_value: null
      versioning: false
  - collection: pages
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: pages
      color: null
      display_template: "{{title}}"
      group: null
      hidden: false
      icon: article
      item_duplication_fields: []
      note: null
      preview_url: null
      singleton: false
      sort: 1
      sort_field: null
      translations: null
      unarchive_value: null
      versioning: true
    schema:
      name: pages
  - collection: pages_page_blocks
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: pages_page_blocks
      color: null
      display_template: null
      group: null
      hidden: true
      icon: import_export
      item_duplication_fields: null
      note: null
      preview_url: null
      singleton: false
      sort: 3
      sort_field: null
      translations: null
      unarchive_value: null
      versioning: false
    schema:
      name: pages_page_blocks
fields:
  - collection: pages
    field: id
    type: uuid
    meta:
      collection: pages
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: 1
      special:
        - uuid
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: id
      table: pages
      data_type: uuid
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: true
      is_indexed: false
      is_primary_key: true
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: pages
    field: title
    type: string
    meta:
      collection: pages
      conditions: null
      display: null
      display_options: null
      field: title
      group: content
      hidden: false
      interface: input
      note: null
      options:
        iconLeft: abc
      readonly: false
      required: true
      sort: 1
      special: null
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: title
      table: pages
      data_type: character varying
      default_value: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: true
      is_indexed: true
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: pages
    field: slug
    type: string
    meta:
      collection: pages
      conditions: null
      display: null
      display_options: null
      field: slug
      group: content
      hidden: false
      interface: input
      note: null
      options:
        iconLeft: add_link
        slug: true
      readonly: false
      required: true
      sort: 2
      special: null
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: slug
      table: pages
      data_type: character varying
      default_value: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: true
      is_indexed: true
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: pages
    field: seo
    type: json
    meta:
      collection: pages
      conditions: null
      display: seo-display
      display_options:
        format: false
        showAsDot: true
      field: seo
      group: meta_tabs
      hidden: false
      interface: seo-interface
      note: null
      options:
        additionalFields: null
        showFocusKeyphrase: true
        showOgImage: true
        showSearchControls: true
        showSitemap: true
        titleTemplate: null
      readonly: false
      required: false
      sort: 2
      special:
        - cast-json
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: seo
      table: pages
      data_type: json
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: pages
    field: meta_tabs
    type: alias
    meta:
      collection: pages
      conditions: null
      display: null
      display_options: null
      field: meta_tabs
      group: null
      hidden: false
      interface: group-tabs
      note: null
      options: null
      readonly: false
      required: false
      sort: 2
      special:
        - alias
        - no-data
        - group
      translations: null
      validation: null
      validation_message: null
      width: full
  - collection: pages
    field: page_blocks
    type: alias
    meta:
      collection: pages
      conditions: null
      display: null
      display_options: null
      field: page_blocks
      group: content
      hidden: false
      interface: list-m2a
      note: null
      options: null
      readonly: false
      required: false
      sort: 3
      special:
        - m2a
      translations: null
      validation: null
      validation_message: null
      width: full
  - collection: pages
    field: content
    type: alias
    meta:
      collection: pages
      conditions: null
      display: null
      display_options: null
      field: content
      group: meta_tabs
      hidden: false
      interface: group-raw
      note: null
      options: null
      readonly: false
      required: false
      sort: 1
      special:
        - alias
        - no-data
        - group
      translations: null
      validation: null
      validation_message: null
      width: full
  - collection: pages
    field: parent_page
    type: uuid
    meta:
      collection: pages
      conditions: null
      display: null
      display_options: null
      field: parent_page
      group: content
      hidden: false
      interface: select-dropdown-m2o
      note: null
      options:
        enableCreate: false
        filter:
          _and:
            - id:
                _neq: null
        template: "{{title}}"
      readonly: false
      required: false
      sort: 4
      special:
        - m2o
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: parent_page
      table: pages
      data_type: uuid
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: pages
      foreign_key_column: id
  - collection: pages_page_blocks
    field: id
    type: integer
    meta:
      collection: pages_page_blocks
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: null
      note: null
      options: null
      readonly: false
      required: false
      sort: 1
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: id
      table: pages_page_blocks
      data_type: integer
      default_value: nextval('pages_page_blocks_id_seq'::regclass)
      max_length: null
      numeric_precision: 32
      numeric_scale: 0
      is_nullable: false
      is_unique: true
      is_indexed: false
      is_primary_key: true
      is_generated: false
      generation_expression: null
      has_auto_increment: true
      foreign_key_table: null
      foreign_key_column: null
  - collection: pages_page_blocks
    field: pages_id
    type: uuid
    meta:
      collection: pages_page_blocks
      conditions: null
      display: null
      display_options: null
      field: pages_id
      group: null
      hidden: true
      interface: null
      note: null
      options: null
      readonly: false
      required: false
      sort: 2
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: pages_id
      table: pages_page_blocks
      data_type: uuid
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: pages
      foreign_key_column: id
  - collection: pages_page_blocks
    field: item
    type: string
    meta:
      collection: pages_page_blocks
      conditions: null
      display: null
      display_options: null
      field: item
      group: null
      hidden: true
      interface: null
      note: null
      options: null
      readonly: false
      required: false
      sort: 3
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: item
      table: pages_page_blocks
      data_type: character varying
      default_value: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: pages_page_blocks
    field: sort
    type: integer
    meta:
      collection: pages_page_blocks
      conditions: null
      display: null
      display_options: null
      field: sort
      group: null
      hidden: true
      interface: null
      note: null
      options: null
      readonly: false
      required: false
      sort: 4
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: sort
      table: pages_page_blocks
      data_type: integer
      default_value: null
      max_length: null
      numeric_precision: 32
      numeric_scale: 0
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: pages_page_blocks
    field: collection
    type: string
    meta:
      collection: pages_page_blocks
      conditions: null
      display: null
      display_options: null
      field: collection
      group: null
      hidden: true
      interface: null
      note: null
      options: null
      readonly: false
      required: false
      sort: 5
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: collection
      table: pages_page_blocks
      data_type: character varying
      default_value: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
relations:
  - collection: pages
    field: parent_page
    related_collection: pages
    meta:
      junction_field: null
      many_collection: pages
      many_field: parent_page
      one_allowed_collections: null
      one_collection: pages
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    schema:
      table: pages
      column: parent_page
      foreign_key_table: pages
      foreign_key_column: id
      constraint_name: pages_parent_page_foreign
      on_update: NO ACTION
      on_delete: NO ACTION
  - collection: pages_page_blocks
    field: item
    related_collection: null
    meta:
      junction_field: pages_id
      many_collection: pages_page_blocks
      many_field: item
      one_allowed_collections: []
      one_collection: null
      one_collection_field: collection
      one_deselect_action: nullify
      one_field: null
      sort_field: null
  - collection: pages_page_blocks
    field: pages_id
    related_collection: pages
    meta:
      junction_field: item
      many_collection: pages_page_blocks
      many_field: pages_id
      one_allowed_collections: null
      one_collection: pages
      one_collection_field: null
      one_deselect_action: nullify
      one_field: page_blocks
      sort_field: sort
    schema:
      table: pages_page_blocks
      column: pages_id
      foreign_key_table: pages
      foreign_key_column: id
      constraint_name: pages_page_blocks_pages_id_foreign
      on_update: NO ACTION
      on_delete: SET NULL
